### ISSUE TITLE
Remove DSStore files

### ISSUE THREAD

**Issue by MichaelCurrin** [Maxence-L/notenote.link#1]
These are specific to a machine and a temporary.

I recommend deleting all .DS_Store files and adding .DS_Store to .gitignore

**Comment by Maxence-L** [comment]
Done, thank you very much for pointing this !

**Comment by fmoledina** [comment]
@Maxence-L Also ensure to add `**/._.DS_Store` in `.gitignore` as well, in order to ignore .DS_Store files in subfolders. There still is one in the `_notes` folder at the moment.

**Comment by MichaelCurrin** [comment]
Git ignore file supports nesting already

This is sufficient to cover at the root and all levels down.
```
.DS_STORE
```

The thing is that if a file is already in source control, adding to ignore rules won't delete it. So the owner just needs to delete the file from the repo and then the ignore rule will ensure they don't get added back

**Comment by fmoledina** [comment]
Ah, thanks. That makes sense.

**Comment by Maxence-L** [comment]
I cleaned the DS_Store files. Thanks for your advice !
