### ISSUE TITLE
Seasons explanation

### ISSUE THREAD

**Issue by bocsardigergely** [Maxence-L/notenote.link#7]
Hello! 
First of all, thank you so much for this repo, it really is a wonderful resource, and it fills a huge void imho.
I don't know if the  Issues is the right place for this, but could you explain the seasons' function in the front matter? I tried playing around with it, but couldn't figure out what they were for, but I am curious.

Thanks!

**Comment by Maxence-L** [comment]
Hi ! Did you find out ? Well, at first I thought about it in a digital garden way : notes grow as you gain knowledge (*winter*>*spring*), until a point  where you've understood well enough the topic (*summer*) that you feel that the note is not accurate anymore, and you need to redo it (*autumn*).

How does it work ?

You can, in frontmatter, set 

---
title : My Note
tags : my_tags
season : summer
---

It displays a "tag" pill at the end of the note. Besides the "feed" you get on the home page is ordered by quality : "summer" notes first, "winter" last, autumn do not get shown as they need a redo.

I hope it helps, it's just a quirky feature that felt more "human" to me. You can remove it by following the guide in the readme.

**Comment by bocsardigergely** [comment]
Yes, I have found the explanation in the [special features](https://notenote.link/notes/how-to-use-the-special-features) page, which I ignore because I was already familiar with the simply jekyll syntax. So the problem is resolved, that is why I closed the issue.
Thanks a lot tho! :D
